# Generated by Django 5.1 on 2024-10-05 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_orderitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='notification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='myapp.order'),
        ),
    ]
